// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicArrowDown: typeof import('~icons/cosmic/arrow-down')['default']
    ICosmicArrowLeft: typeof import('~icons/cosmic/arrow-left')['default']
    ICosmicArrowRight: typeof import('~icons/cosmic/arrow-right')['default']
    ICosmicArrowUp: typeof import('~icons/cosmic/arrow-up')['default']
    ICosmicAtom: typeof import('~icons/cosmic/atom')['default']
    ICosmicBoard: typeof import('~icons/cosmic/board')['default']
    ICosmicCaution: typeof import('~icons/cosmic/caution')['default']
  }
}

export { }
