// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicH: typeof import('~icons/cosmic/h')['default']
    ICosmicLock: typeof import('~icons/cosmic/lock')['default']
    ICosmicOffsetX: typeof import('~icons/cosmic/offset-x')['default']
    ICosmicOffsetY: typeof import('~icons/cosmic/offset-y')['default']
    ICosmicScaleX: typeof import('~icons/cosmic/scale-x')['default']
    ICosmicScaleY: typeof import('~icons/cosmic/scale-y')['default']
    ICosmicW: typeof import('~icons/cosmic/w')['default']
    ICosmicX: typeof import('~icons/cosmic/x')['default']
    ICosmicY: typeof import('~icons/cosmic/y')['default']
  }
}

export { }
