// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicBorder: typeof import('~icons/cosmic/border')['default']
    ICosmicGridOutline: typeof import('~icons/cosmic/grid-outline')['default']
    ICosmicHorizonalWidth: typeof import('~icons/cosmic/horizonal-width')['default']
    ICosmicLink: typeof import('~icons/cosmic/link')['default']
    ICosmicMinus: typeof import('~icons/cosmic/minus')['default']
    ICosmicMore: typeof import('~icons/cosmic/more')['default']
    ICosmicPlus: typeof import('~icons/cosmic/plus')['default']
    ICosmicTextCenter: typeof import('~icons/cosmic/text-center')['default']
    ICosmicTextEven: typeof import('~icons/cosmic/text-even')['default']
    ICosmicTextLeft: typeof import('~icons/cosmic/text-left')['default']
    ICosmicTextRight: typeof import('~icons/cosmic/text-right')['default']
  }
}

export { }
