// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicBorder: typeof import('~icons/cosmic/border')['default']
    ICosmicCircleend: typeof import('~icons/cosmic/circleend')['default']
    ICosmicEndpoint: typeof import('~icons/cosmic/endpoint')['default']
    ICosmicGridOutline: typeof import('~icons/cosmic/grid-outline')['default']
    ICosmicInnerPoint: typeof import('~icons/cosmic/inner-point')['default']
    ICosmicLock: typeof import('~icons/cosmic/lock')['default']
    ICosmicMinus: typeof import('~icons/cosmic/minus')['default']
    ICosmicMore: typeof import('~icons/cosmic/more')['default']
    ICosmicPlus: typeof import('~icons/cosmic/plus')['default']
    ICosmicSquare: typeof import('~icons/cosmic/square')['default']
    ICosmicTextEven: typeof import('~icons/cosmic/text-even')['default']
  }
}

export { }
