// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicCheck: typeof import('~icons/cosmic/check')['default']
    ICosmicClose: typeof import('~icons/cosmic/close')['default']
  }
}

export { }
