// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicMinus: typeof import('~icons/cosmic/minus')['default']
    ICosmicPlus: typeof import('~icons/cosmic/plus')['default']
  }
}

export { }
