// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicArrowDown: typeof import('~icons/cosmic/arrow-down')['default']
    ICosmicArrowUp: typeof import('~icons/cosmic/arrow-up')['default']
    ICosmicPlus: typeof import('~icons/cosmic/plus')['default']
    ICosmicTrash: typeof import('~icons/cosmic/trash')['default']
    ICosmicX: typeof import('~icons/cosmic/x')['default']
    ICosmicY: typeof import('~icons/cosmic/y')['default']
  }
}

export { }
