// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicArrowDown: typeof import('~icons/cosmic/arrow-down')['default']
    ICosmicCaution: typeof import('~icons/cosmic/caution')['default']
    ICosmicFuzzy: typeof import('~icons/cosmic/fuzzy')['default']
    ICosmicGridOutline: typeof import('~icons/cosmic/grid-outline')['default']
    ICosmicLock: typeof import('~icons/cosmic/lock')['default']
    ICosmicMinus: typeof import('~icons/cosmic/minus')['default']
    ICosmicMore: typeof import('~icons/cosmic/more')['default']
    ICosmicPlus: typeof import('~icons/cosmic/plus')['default']
    ICosmicSun: typeof import('~icons/cosmic/sun')['default']
    ICosmicVerticalHeight: typeof import('~icons/cosmic/vertical-height')['default']
  }
}

export { }
