// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicArrowDown: typeof import('~icons/cosmic/arrow-down')['default']
    ICosmicFont: typeof import('~icons/cosmic/font')['default']
    ICosmicGridOutline: typeof import('~icons/cosmic/grid-outline')['default']
    ICosmicLineHeight: typeof import('~icons/cosmic/line-height')['default']
    ICosmicLinkedSquare: typeof import('~icons/cosmic/linked-square')['default']
    ICosmicSun: typeof import('~icons/cosmic/sun')['default']
    ICosmicTextCenter: typeof import('~icons/cosmic/text-center')['default']
    ICosmicTextEven: typeof import('~icons/cosmic/text-even')['default']
    ICosmicTextLeft: typeof import('~icons/cosmic/text-left')['default']
    ICosmicTextRight: typeof import('~icons/cosmic/text-right')['default']
    ICosmicVerticalHeight: typeof import('~icons/cosmic/vertical-height')['default']
    ICosmicWidthAuto: typeof import('~icons/cosmic/width-auto')['default']
  }
}

export { }
