// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicBoard: typeof import('~icons/cosmic/board')['default']
    ICosmicDark: typeof import('~icons/cosmic/dark')['default']
    ICosmicPlus: typeof import('~icons/cosmic/plus')['default']
    ICosmicSun: typeof import('~icons/cosmic/sun')['default']
  }
}

export { }
