// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicDark: typeof import('~icons/cosmic/dark')['default']
    ICosmicGridOutline: typeof import('~icons/cosmic/grid-outline')['default']
    ICosmicLink: typeof import('~icons/cosmic/link')['default']
    ICosmicMore: typeof import('~icons/cosmic/more')['default']
    ICosmicPlus: typeof import('~icons/cosmic/plus')['default']
    ICosmicQuestion: typeof import('~icons/cosmic/question')['default']
    ICosmicSun: typeof import('~icons/cosmic/sun')['default']
    ICosmicText: typeof import('~icons/cosmic/text')['default']
  }
}

export { }
