// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicDark: typeof import('~icons/cosmic/dark')['default']
    ICosmicLock: typeof import('~icons/cosmic/lock')['default']
    ICosmicMore: typeof import('~icons/cosmic/more')['default']
    ICosmicNight: typeof import('~icons/cosmic/night')['default']
    ICosmicSun: typeof import('~icons/cosmic/sun')['default']
  }
}

export { }
