// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicBorder: typeof import('~icons/cosmic/border')['default']
    ICosmicContain: typeof import('~icons/cosmic/contain')['default']
    ICosmicCorner: typeof import('~icons/cosmic/corner')['default']
    ICosmicDark: typeof import('~icons/cosmic/dark')['default']
    ICosmicFeedback: typeof import('~icons/cosmic/feedback')['default']
    ICosmicInput: typeof import('~icons/cosmic/input')['default']
    ICosmicIntersection: typeof import('~icons/cosmic/intersection')['default']
    ICosmicLayout: typeof import('~icons/cosmic/layout')['default']
    ICosmicLock: typeof import('~icons/cosmic/lock')['default']
    ICosmicMinus: typeof import('~icons/cosmic/minus')['default']
    ICosmicMore: typeof import('~icons/cosmic/more')['default']
    ICosmicNight: typeof import('~icons/cosmic/night')['default']
    ICosmicPlus: typeof import('~icons/cosmic/plus')['default']
    ICosmicScale: typeof import('~icons/cosmic/scale')['default']
    ICosmicShadow: typeof import('~icons/cosmic/shadow')['default']
    ICosmicSun: typeof import('~icons/cosmic/sun')['default']
    ICosmicText: typeof import('~icons/cosmic/text')['default']
  }
}

export { }
