// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicArrowDown: typeof import('~icons/cosmic/arrow-down')['default']
    ICosmicArrowUp: typeof import('~icons/cosmic/arrow-up')['default']
    ICosmicBoard: typeof import('~icons/cosmic/board')['default']
    ICosmicDown: typeof import('~icons/cosmic/down')['default']
    ICosmicPlay: typeof import('~icons/cosmic/play')['default']
    ICosmicScrollX: typeof import('~icons/cosmic/scroll-x')['default']
    ICosmicScrollY: typeof import('~icons/cosmic/scroll-y')['default']
    ICosmicSelectOff: typeof import('~icons/cosmic/select-off')['default']
    ICosmicSelectOn: typeof import('~icons/cosmic/select-on')['default']
    ICosmicSelectUpDown: typeof import('~icons/cosmic/select-up-down')['default']
    ICosmicSelectUpUp: typeof import('~icons/cosmic/select-up-up')['default']
    ICosmicTextEven: typeof import('~icons/cosmic/text-even')['default']
  }
}

export { }
