// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicArrowDown: typeof import('~icons/cosmic/arrow-down')['default']
    ICosmicArrowUp: typeof import('~icons/cosmic/arrow-up')['default']
    ICosmicLine: typeof import('~icons/cosmic/line')['default']
  }
}

export { }
