// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicGridOutline: typeof import('~icons/cosmic/grid-outline')['default']
    ICosmicLinkedSquare: typeof import('~icons/cosmic/linked-square')['default']
    ICosmicLock: typeof import('~icons/cosmic/lock')['default']
    ICosmicMinus: typeof import('~icons/cosmic/minus')['default']
    ICosmicMore: typeof import('~icons/cosmic/more')['default']
    ICosmicPlus: typeof import('~icons/cosmic/plus')['default']
    ICosmicSquare: typeof import('~icons/cosmic/square')['default']
  }
}

export { }
