// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EditableText: typeof import('./src/components/editable-text.vue')['default']
    Properties: typeof import('./src/components/proposal/properties.vue')['default']
  }
}

export { }
