// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Construction: typeof import('./src/components/proposal/construction.vue')['default']
    EditableText: typeof import('./src/components/editable-text.vue')['default']
    Panel: typeof import('./src/components/proposal/panel.vue')['default']
    Property: typeof import('./src/components/proposal/property.vue')['default']
    Variant: typeof import('./src/components/proposal/variant.vue')['default']
  }
}

export { }
