// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicBoard: typeof import('~icons/cosmic/board')['default']
    ICosmicEyeOpen: typeof import('~icons/cosmic/eye-open')['default']
    ICosmicRoundedSquare: typeof import('~icons/cosmic/rounded-square')['default']
    ICosmicSearch: typeof import('~icons/cosmic/search')['default']
  }
}

export { }
