// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicBoard: typeof import('~icons/cosmic/board')['default']
    ICosmicComp: typeof import('~icons/cosmic/comp')['default']
    ICosmicEyeOpen: typeof import('~icons/cosmic/eye-open')['default']
    ICosmicSearch: typeof import('~icons/cosmic/search')['default']
    ICosmicSquare: typeof import('~icons/cosmic/square')['default']
    ICosmicText: typeof import('~icons/cosmic/text')['default']
  }
}

export { }
