// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicArrowDown: typeof import('~icons/cosmic/arrow-down')['default']
    ICosmicCaution: typeof import('~icons/cosmic/caution')['default']
    ICosmicComp: typeof import('~icons/cosmic/comp')['default']
    ICosmicMore: typeof import('~icons/cosmic/more')['default']
  }
}

export { }
